# ============================================================
# config_optimized.py — Auto-generated by optimize.py
# Generated  : 2026-03-17 12:52 UTC
# Assets     : BTC,ETH,SOL
# Trials     : 150
# Objective  : calmar
# Mean OOS Sharpe : 2.8521
#
# REVIEW BEFORE DEPLOYING — copy desired values into config.py
# ============================================================

# Walk-forward OOS window results:
#   2024-12 → 2025-03  trades=99  sharpe=3.353  return=+8.1%  dd=-2.8%
#   2025-03 → 2025-06  trades=87  sharpe=0.319  return=+0.5%  dd=-1.9%
#   2025-06 → 2025-09  trades=90  sharpe=1.865  return=+1.7%  dd=-1.4%
#   2025-09 → 2025-12  trades=115  sharpe=3.046  return=+6.2%  dd=-2.1%
#   2025-12 → 2026-03  trades=108  sharpe=5.678  return=+12.3%  dd=-2.2%

# ── Optimised parameters ──────────────────────────────────────
MIN_CONVICTION_SCORE         = 12.600477  # was 12.74
ADX_TREND_THRESHOLD          = 26.000000  # was 24.0
ATR_STOP_MULTIPLIER          = 3.096752  # was 3.0833
ATR_TP_MULTIPLIER            = 1.561616  # was 2.538
TRAIL_ACTIVATION_ATR         = 0.510807  # was 2.2968
TRAIL_ATR_MULTIPLIER         = 0.500679  # was 0.8826
KELLY_FRACTION               = 0.043857  # was 0.0493
TIER_CORR_FACTOR             = 0.947996  # was 0.7986
VOL_REGIME_LOW               = 0.808206  # was 0.7
VOL_REGIME_MIN               = 0.634036  # was 0.6
MA200_NEAR_BAND              = 0.142691  # was 0.15
MA200_FAR_BAND               = 0.624506  # was 0.35

